name: Build a release

on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/x86_64-pc-windows-gnu/release/socks-bin.exe
